apiVersion: v1
kind: Namespace
metadata:
  name: expand-contract-db-pattern
---
apiVersion: v1
kind: Service
metadata:
  namespace: expand-contract-db-pattern
  name: db-service
spec:
  selector:
    role: db
  ports:
    - port: 5432
      nodePort: 30003
      targetPort: 5432
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: expand-contract-db-pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: example-db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin