apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: custom
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: customer.domain
      http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 8080
